### ISSUE TITLE
Unable to make

### ISSUE THREAD

**Issue by wthe2004** [DRCL-USC/Hector_Simulation#19]
I was trying to build this repository on my computer(Ubuntu 20.04 ROS Neotic) but the output is like this

```bash
catkin_make -DCMAKE_BUILD_TYPE=Release
Base path: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws
Source space: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/src
Build space: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/build
Devel space: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel
Install space: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/install
####
#### Running command: "cmake /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/src -DCMAKE_BUILD_TYPE=Release -DCATKIN_DEVEL_PREFIX=/home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/install -G Unix Makefiles" in "/home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/build"
####
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/hwt-ubuntu/Documents/limxdynamics/pointfoot-gazebo-ros/install;/opt/ros/noetic
-- This workspace overlays: /home/hwt-ubuntu/Documents/limxdynamics/pointfoot-gazebo-ros/install;/opt/ros/noetic
-- Found PythonInterp: /home/hwt-ubuntu/miniconda3/envs/ros-neotic/bin/python3 (found suitable version "3.8.18", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /home/hwt-ubuntu/miniconda3/envs/ros-neotic/bin/python3
-- Using Debian Python package layout
-- Found PY_em: /home/hwt-ubuntu/miniconda3/envs/ros-neotic/lib/python3.8/site-packages/em.py
-- Using empy: /home/hwt-ubuntu/miniconda3/envs/ros-neotic/lib/python3.8/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/build/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /home/hwt-ubuntu/miniconda3/envs/ros-neotic/bin/python3 (found version "3.8.18")
-- Found Threads: TRUE
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 6 packages in topological order:
-- ~~  - hector_description
-- ~~  - unitree_legged_msgs
-- ~~  - unitree_legged_control
-- ~~  - hector_control
-- ~~  - unitree_controller
-- ~~  - unitree_gazebo
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'hector_description'
-- ==> add_subdirectory(hector_description)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'unitree_legged_msgs'
-- ==> add_subdirectory(unitree_ros/unitree_legged_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- unitree_legged_msgs: 11 messages, 0 services
-- +++ processing catkin package: 'unitree_legged_control'
-- ==> add_subdirectory(unitree_ros/unitree_legged_control)
-- +++ processing catkin package: 'hector_control'
-- ==> add_subdirectory(hector_control)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'bullet>=2.82'
--   Found bullet, version 2.88
-- Found ccd: /usr/include (found suitable version "2.0", minimum required is "2.0")
-- Found fcl: /opt/ros/noetic/include (found suitable version "0.6.1", minimum required is "0.3.2")
-- Found assimp: /usr/include (found version "5.0.0")
-- Found DART: /usr/include (Required is at least version "6.6") found components: dart
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.40.0") found components: thread system filesystem program_options regex iostreams date_time
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1")
-- Looking for ignition-math6 -- found version 6.15.1
-- Searching for dependencies of ignition-math6
-- Looking for OGRE...
-- OGRE_PREFIX_WATCH changed.
-- Checking for module 'OGRE'
--   Found OGRE, version 1.9.0
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Looking for ignition-math6 -- found version 6.15.1
-- Looking for ignition-transport8 -- found version 8.3.0
-- Searching for dependencies of ignition-transport8
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found suitable version "3.6.1", minimum required is "3")
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.3.2
-- Found ZeroMQ: TRUE (Required is at least version "4")
-- Checking for module 'uuid'
--   Found uuid, version 2.34.0
-- Found UUID: TRUE
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Searching for dependencies of ignition-msgs5
-- Looking for ignition-math6 -- found version 6.15.1
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.2.0
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Looking for ignition-common3 -- found version 3.14.2
-- Searching for dependencies of ignition-common3
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- Found DL: TRUE
-- Searching for <ignition-common3> component [graphics]
-- Looking for ignition-common3-graphics -- found version 3.14.2
-- Searching for dependencies of ignition-common3-graphics
-- Looking for ignition-math6 -- found version 6.15.1
-- Looking for ignition-fuel_tools4 -- found version 4.6.0
-- Searching for dependencies of ignition-fuel_tools4
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Found JSONCPP: TRUE
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.2.2
-- Found YAML: TRUE
-- Checking for module 'libzip'
--   Found libzip, version 1.5.1
-- Found ZIP: TRUE
-- Looking for ignition-common3 -- found version 3.14.2
-- Looking for ignition-math6 -- found version 6.15.1
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0")
-- +++ processing catkin package: 'unitree_controller'
-- ==> add_subdirectory(unitree_ros/unitree_controller)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found DART: /usr/include (Required is at least version "6.6") found components: dart
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.40.0") found components: thread system filesystem program_options regex iostreams date_time
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1")
-- Looking for ignition-math6 -- found version 6.15.1
-- Searching for dependencies of ignition-math6
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Looking for ignition-math6 -- found version 6.15.1
-- Looking for ignition-transport8 -- found version 8.3.0
-- Searching for dependencies of ignition-transport8
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found suitable version "3.6.1", minimum required is "3")
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.3.2
-- Checking for module 'uuid'
--   Found uuid, version 2.34.0
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Searching for dependencies of ignition-msgs5
-- Looking for ignition-math6 -- found version 6.15.1
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.2.0
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Looking for ignition-common3 -- found version 3.14.2
-- Searching for dependencies of ignition-common3
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- Searching for <ignition-common3> component [graphics]
-- Looking for ignition-common3-graphics -- found version 3.14.2
-- Searching for dependencies of ignition-common3-graphics
-- Looking for ignition-math6 -- found version 6.15.1
-- Looking for ignition-fuel_tools4 -- found version 4.6.0
-- Searching for dependencies of ignition-fuel_tools4
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.2.2
-- Checking for module 'libzip'
--   Found libzip, version 1.5.1
-- Looking for ignition-common3 -- found version 3.14.2
-- Looking for ignition-math6 -- found version 6.15.1
-- Looking for ignition-msgs5 -- found version 5.10.0
-- +++ processing catkin package: 'unitree_gazebo'
-- ==> add_subdirectory(unitree_ros/unitree_gazebo)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found DART: /usr/include (Required is at least version "6.6") found components: dart
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1")
-- Looking for ignition-math6 -- found version 6.15.1
-- Searching for dependencies of ignition-math6
-- Looking for OGRE...
-- Found Ogre Ghadamon (1.9.0)
-- Found OGRE: optimized;/usr/lib/x86_64-linux-gnu/libOgreMain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreMain.so
-- Looking for OGRE_Paging...
-- Found OGRE_Paging: optimized;/usr/lib/x86_64-linux-gnu/libOgrePaging.so;debug;/usr/lib/x86_64-linux-gnu/libOgrePaging.so
-- Looking for OGRE_Terrain...
-- Found OGRE_Terrain: optimized;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so;debug;/usr/lib/x86_64-linux-gnu/libOgreTerrain.so
-- Looking for OGRE_Property...
-- Found OGRE_Property: optimized;/usr/lib/x86_64-linux-gnu/libOgreProperty.so;debug;/usr/lib/x86_64-linux-gnu/libOgreProperty.so
-- Looking for OGRE_RTShaderSystem...
-- Found OGRE_RTShaderSystem: optimized;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so;debug;/usr/lib/x86_64-linux-gnu/libOgreRTShaderSystem.so
-- Looking for OGRE_Volume...
-- Found OGRE_Volume: optimized;/usr/lib/x86_64-linux-gnu/libOgreVolume.so;debug;/usr/lib/x86_64-linux-gnu/libOgreVolume.so
-- Looking for OGRE_Overlay...
-- Found OGRE_Overlay: optimized;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so;debug;/usr/lib/x86_64-linux-gnu/libOgreOverlay.so
-- Looking for ignition-math6 -- found version 6.15.1
-- Looking for ignition-transport8 -- found version 8.3.0
-- Searching for dependencies of ignition-transport8
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found suitable version "3.6.1", minimum required is "3")
-- Config-file not installed for ZeroMQ -- checking for pkg-config
-- Checking for module 'libzmq >= 4'
--   Found libzmq , version 4.3.2
-- Checking for module 'uuid'
--   Found uuid, version 2.34.0
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Searching for dependencies of ignition-msgs5
-- Looking for ignition-math6 -- found version 6.15.1
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.2.0
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Looking for ignition-common3 -- found version 3.14.2
-- Searching for dependencies of ignition-common3
-- Looking for dlfcn.h - found
-- Looking for libdl - found
-- Searching for <ignition-common3> component [graphics]
-- Looking for ignition-common3-graphics -- found version 3.14.2
-- Searching for dependencies of ignition-common3-graphics
-- Looking for ignition-math6 -- found version 6.15.1
-- Looking for ignition-fuel_tools4 -- found version 4.6.0
-- Searching for dependencies of ignition-fuel_tools4
-- Checking for module 'jsoncpp'
--   Found jsoncpp, version 1.7.4
-- Checking for module 'yaml-0.1'
--   Found yaml-0.1, version 0.2.2
-- Checking for module 'libzip'
--   Found libzip, version 1.5.1
-- Looking for ignition-common3 -- found version 3.14.2
-- Looking for ignition-math6 -- found version 6.15.1
-- Looking for ignition-msgs5 -- found version 5.10.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/build
####
#### Running command: "make -j24 -l24" in "/home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/build"
####
Scanning dependencies of target std_msgs_generate_messages_cpp
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_HighState
Scanning dependencies of target geometry_msgs_generate_messages_cpp
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_MotorCmd
Scanning dependencies of target sensor_msgs_generate_messages_cpp
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_LED
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_MotorState
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_BmsState
Scanning dependencies of target sensor_msgs_generate_messages_py
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_HighCmd
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_LowCmd
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_BmsCmd
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_LowState
Scanning dependencies of target geometry_msgs_generate_messages_py
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_Cartesian
Scanning dependencies of target _unitree_legged_msgs_generate_messages_check_deps_IMU
Scanning dependencies of target std_msgs_generate_messages_py
Scanning dependencies of target geometry_msgs_generate_messages_nodejs
Scanning dependencies of target std_msgs_generate_messages_nodejs
Scanning dependencies of target sensor_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_cpp
Scanning dependencies of target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_cpp
Scanning dependencies of target geometry_msgs_generate_messages_lisp
Scanning dependencies of target std_msgs_generate_messages_lisp
Scanning dependencies of target std_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_lisp
Scanning dependencies of target sensor_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_py
Scanning dependencies of target geometry_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_eus
Scanning dependencies of target unitree_move_kinetic
Scanning dependencies of target qpOASES
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_MotorState
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_IMU
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_LED
Scanning dependencies of target unitreeFootContactPlugin
Scanning dependencies of target unitree_external_force
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_BmsCmd
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_Cartesian
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_LowState
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_HighState
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_MotorCmd
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_BmsState
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_HighCmd
[  0%] Built target _unitree_legged_msgs_generate_messages_check_deps_LowCmd
[  1%] Building CXX object unitree_ros/unitree_controller/CMakeFiles/unitree_move_kinetic.dir/src/move_publisher.cpp.o
Scanning dependencies of target unitree_legged_msgs_generate_messages_cpp
Scanning dependencies of target unitree_legged_msgs_generate_messages_py
Scanning dependencies of target unitree_legged_msgs_generate_messages_nodejs
Scanning dependencies of target unitree_legged_msgs_generate_messages_eus
[  2%] Building CXX object unitree_ros/unitree_controller/CMakeFiles/unitree_external_force.dir/src/external_force.cpp.o
Scanning dependencies of target unitree_legged_msgs_generate_messages_lisp
[  3%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/BLASReplacement.cpp.o
[  4%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/Bounds.cpp.o
[  5%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/LAPACKReplacement.cpp.o
[  6%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/MessageHandling.cpp.o
[  7%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/Constraints.cpp.o
[  9%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/Flipper.cpp.o
[  9%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/Indexlist.cpp.o
[  9%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/OQPinterface.cpp.o
[ 10%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/Options.cpp.o
[ 10%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/QProblemB.cpp.o
[ 11%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/Matrices.cpp.o
[ 12%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/SQProblemSchur.cpp.o
[ 13%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/SQProblem.cpp.o
[ 14%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/QProblem.cpp.o
[ 14%] Generating Python from MSG unitree_legged_msgs/MotorCmd
[ 15%] Generating Javascript code from unitree_legged_msgs/MotorCmd.msg
[ 17%] Generating C++ code from unitree_legged_msgs/MotorCmd.msg
[ 18%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/SolutionAnalysis.cpp.o
[ 19%] Generating C++ code from unitree_legged_msgs/MotorState.msg
[ 20%] Generating EusLisp code from unitree_legged_msgs/MotorCmd.msg
[ 21%] Generating Lisp code from unitree_legged_msgs/MotorCmd.msg
Traceback (most recent call last):
  File "/opt/ros/noetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 49, in <module>
    genmsg.template_tools.generate_from_command_line_options(
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
Traceback (most recent call last):
  File "/opt/ros/noetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 49, in <module>
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
    genmsg.template_tools.generate_from_command_line_options(
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 93, in _generate_msg_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
    _generate_from_spec(input_file,
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 93, in _generate_msg_from_file
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: module 'em' has no attribute 'RAW_OPT'
    _generate_from_spec(input_file,
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: module 'em' has no attribute 'RAW_OPT'
make[2]: *** [unitree_ros/unitree_legged_msgs/CMakeFiles/unitree_legged_msgs_generate_messages_cpp.dir/build.make:79: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel/include/unitree_legged_msgs/MotorState.h] Error 1
make[2]: *** Deleting file '/home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel/include/unitree_legged_msgs/MotorState.h'
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [unitree_ros/unitree_legged_msgs/CMakeFiles/unitree_legged_msgs_generate_messages_cpp.dir/build.make:73: /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel/include/unitree_legged_msgs/MotorCmd.h] Error 1
make[2]: *** Deleting file '/home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel/include/unitree_legged_msgs/MotorCmd.h'
[ 22%] Generating Lisp code from unitree_legged_msgs/MotorState.msg
make[1]: *** [CMakeFiles/Makefile2:2262: unitree_ros/unitree_legged_msgs/CMakeFiles/unitree_legged_msgs_generate_messages_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 23%] Generating Javascript code from unitree_legged_msgs/MotorState.msg
[ 23%] Building CXX object unitree_ros/unitree_gazebo/CMakeFiles/unitreeFootContactPlugin.dir/plugin/foot_contact_plugin.cc.o
[ 24%] Generating EusLisp code from unitree_legged_msgs/MotorState.msg
[ 25%] Generating Python from MSG unitree_legged_msgs/MotorState
[ 26%] Generating Python from MSG unitree_legged_msgs/BmsCmd
[ 27%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/SubjectTo.cpp.o
[ 28%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/SparseSolver.cpp.o
[ 29%] Generating Lisp code from unitree_legged_msgs/BmsCmd.msg
[ 30%] Generating Javascript code from unitree_legged_msgs/BmsCmd.msg
[ 31%] Generating Lisp code from unitree_legged_msgs/BmsState.msg
[ 32%] Generating Lisp code from unitree_legged_msgs/Cartesian.msg
[ 34%] Building CXX object hector_control/third_party/qpOASES/CMakeFiles/qpOASES.dir/src/Utils.cpp.o
[ 35%] Generating Javascript code from unitree_legged_msgs/BmsState.msg
[ 36%] Generating Lisp code from unitree_legged_msgs/IMU.msg
[ 37%] Generating EusLisp code from unitree_legged_msgs/BmsCmd.msg
[ 37%] Generating EusLisp code from unitree_legged_msgs/Cartesian.msg
[ 38%] Generating EusLisp code from unitree_legged_msgs/BmsState.msg
[ 38%] Generating Javascript code from unitree_legged_msgs/Cartesian.msg
[ 39%] Generating Javascript code from unitree_legged_msgs/LED.msg
[ 40%] Generating Javascript code from unitree_legged_msgs/IMU.msg
[ 40%] Generating Lisp code from unitree_legged_msgs/LowCmd.msg
[ 41%] Generating EusLisp code from unitree_legged_msgs/IMU.msg
[ 42%] Generating Python from MSG unitree_legged_msgs/BmsState
[ 43%] Generating Lisp code from unitree_legged_msgs/LED.msg
[ 45%] Generating Python from MSG unitree_legged_msgs/Cartesian
[ 45%] Generating Lisp code from unitree_legged_msgs/LowState.msg
[ 46%] Generating Python from MSG unitree_legged_msgs/IMU
[ 47%] Generating Python from MSG unitree_legged_msgs/LED
[ 48%] Generating Python from MSG unitree_legged_msgs/LowCmd
[ 48%] Generating Python from MSG unitree_legged_msgs/LowState
[ 51%] Generating Python from MSG unitree_legged_msgs/HighCmd
[ 51%] Generating Javascript code from unitree_legged_msgs/LowCmd.msg
[ 52%] Generating Python from MSG unitree_legged_msgs/HighState
[ 53%] Generating EusLisp code from unitree_legged_msgs/LED.msg
[ 54%] Generating EusLisp code from unitree_legged_msgs/LowCmd.msg
[ 55%] Generating Javascript code from unitree_legged_msgs/LowState.msg
[ 56%] Generating Lisp code from unitree_legged_msgs/HighState.msg
[ 57%] Generating Javascript code from unitree_legged_msgs/HighCmd.msg
[ 58%] Generating Lisp code from unitree_legged_msgs/HighCmd.msg
[ 60%] Generating EusLisp code from unitree_legged_msgs/HighCmd.msg
[ 59%] Generating EusLisp code from unitree_legged_msgs/LowState.msg
[ 61%] Generating EusLisp code from unitree_legged_msgs/HighState.msg
[ 61%] Generating EusLisp manifest code for unitree_legged_msgs
[ 62%] Generating Javascript code from unitree_legged_msgs/HighState.msg
[ 62%] Built target unitree_legged_msgs_generate_messages_lisp
[ 63%] Generating Python msg __init__.py for unitree_legged_msgs
[ 63%] Built target unitree_legged_msgs_generate_messages_nodejs
[ 63%] Built target unitree_legged_msgs_generate_messages_py
[ 63%] Built target unitree_legged_msgs_generate_messages_eus
[ 64%] Linking CXX executable /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel/lib/unitree_controller/unitree_move_kinetic
[ 64%] Built target unitree_move_kinetic
[ 65%] Linking CXX executable /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel/lib/unitree_controller/unitree_external_force
[ 65%] Built target unitree_external_force
[ 67%] Linking CXX shared library /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel/lib/libqpOASES.so
[ 67%] Built target qpOASES
[ 68%] Linking CXX shared library /home/hwt-ubuntu/Documents/limxdynamics/reference/Hector/catkin_ws/devel/lib/libunitreeFootContactPlugin.so
[ 68%] Built target unitreeFootContactPlugin
make: *** [Makefile:141: all] Error 2
Invoking "make -j24 -l24" failed
```

**Comment by junhengl** [comment]
have you tried building it within the \catkin_ws instead of \catkin_ws\build?

**Comment by xiaohai-AI** [comment]
AttributeError: module 'em' has no attribute 'RAW_OPT'
reinstall ros-noetic may be ?
